# Generated by Django 5.2.8 on 2025-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_messages', '0002_chatmessage_updated_at_alter_chatmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
